---
- hosts: localhost
  connection: local
  vars_files:
    vars.yml
  tasks: 
    - name: install base packages
      dnf:
        name: "{{ item }}"
        state: present 
      with_items: 
        - guake
        - docker
        - snapd
        - powertop
        - npm
        - gnome-tweak-tool
        - flatpak
      become: yes
    - name: create snap symlink for classic support
      file: 
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
      become: yes
    - name: install snaps # snap module doesn't come in until 2.8
      command: "snap install {{ item }}"
      become: yes
      with_items: 
        - snap-store
        - slack --classic
        - spotify
        - rambox --classic
    - name: add flathub repo
      command: flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
      become: yes
    - name: 
      flatpak: 
        name: "{{ item }}"
        state: present
      with_items: 
        - chat.rocket.RocketChat
        - org.darktable.Darktable
    - name: install npm items
      npm: 
        name: "{{ item }}"
        state: present
        global: no
        path: ~/npm
      with_items: 
        - electron
        - notion
    - name: install vscode
      include_tasks: vscode.yml 
      become: yes
    - name: Set git email addy
      command: git config --global user.email "{{ git_email }}"