---
- hosts: localhost
  connection: local
  vars_files:
    vars.yml
  tasks: 
    - name: install base packages
      dnf:
        name: "{{ item }}"
        state: present 
      with_items: 
        - guake
        - docker
        - snapd
        - powertop
      become: yes
    - name: create snap symlink for classic support
      file: 
        src: /var/lib/snapd/snap
        dest: /snap
        state: link
      become: yes
    - name: install snaps # snap module doesn't come in until 2.8
      command: "snap install {{ item }}"
      become: yes
      with_items: 
        - snap-store
        - slack --classic
        - rocketchat-desktop
        - spotify
        - rambox
    - name: install vscode
      include_tasks: vscode.yml 
      become: yes
